language: python

python:
    - "3.5"

sudo: required

cache: pip

env:
    - AIL_HOME=$TRAVIS_BUILD_DIR AIL_BIN=$TRAVIS_BUILD_DIR/bin/ \
      AIL_FLASK=$TRAVIS_BUILD_DIR/var/www/ AIL_REDIS=$TRAVIS_BUILD_DIR/redis/src/ \
      AIL_LEVELDB=$TRAVIS_BUILD_DIR/redis-leveldb/ PATH=$AIL_HOME:$AIL_REDIS:$AIL_LEVELDB:$PATH



install:
    - ./installing_deps.sh
    - pip install coveralls codecov

script:
    - pushd bin
    - ./launch_redis.sh
    - ./launch_lvldb.sh
    - ./launch_logs.sh
    - ./launch_queues.sh
    - ./launch_scripts.sh
    - sleep 120
    - ./Shutdown.py
    - popd
    - find logs/* -exec cat {} \;
    - nosetests --with-coverage --cover-package=things -d

notifications:
    email:
        on_success: change
        on_failure: change

after_success:
    - codecov
    - coveralls
