language: python

python:
    - "2.7"

sudo: required

cache: pip

env:
    - AIL_HOME=$TRAVIS_BUILD_DIR AIL_BIN=$TRAVIS_BUILD_DIR/bin/ \
      AIL_FLASK=$TRAVIS_BUILD_DIR/var/www/ AIL_REDIS=$TRAVIS_BUILD_DIR/redis/src/ \
      AIL_LEVELDB=$TRAVIS_BUILD_DIR/redis-leveldb/ PATH=$AIL_HOME:$AIL_REDIS:$AIL_LEVELDB:$PATH



install:
    - ./installing_deps.sh

script:
    - pushd bin
    - ./launch_redis.sh
    - ./launch_lvldb.sh
    - ./launch_logs.sh
    - ./launch_queues.sh
    - ./launch_scripts.sh
    - sleep 120
    - ./Shutdown.py
    - popd
    - find logs/* -exec cat {} \;

notifications:
    email:
        on_success: change
        on_failure: change
