language: python

python:
    - "3.5"

sudo: required

cache: pip

env:
    - AIL_HOME=$TRAVIS_BUILD_DIR AIL_BIN=$TRAVIS_BUILD_DIR/bin/ \
      AIL_FLASK=$TRAVIS_BUILD_DIR/var/www/ AIL_REDIS=$TRAVIS_BUILD_DIR/redis/src/ \
      AIL_LEVELDB=$TRAVIS_BUILD_DIR/redis-leveldb/ PATH=$AIL_HOME:$AIL_REDIS:$AIL_LEVELDB:$PATH



install:
    - ./installing_deps.sh
    - pip install coveralls codecov nose

script:
    - pushd bin
    - ./launch_redis.sh
    - ./launch_lvldb.sh
    - ./launch_logs.sh
    - ./launch_queues.sh
    - nosetests --with-coverage --cover-package=bin -d
    - ls


after_success:
    - codecov
    - coveralls
